<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\**" />
    <Content Remove="Assets\**" />
    <EmbeddedResource Remove="Assets\**" />
    <None Remove="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

</Project>
